language: python

python:
- 2.7
- 3.4
- 3.5
- pypy
- pypy3

env:
- DJANGO_VERSION=1.7.11
- DJANGO_VERSION=1.8.7
- DJANGO_VERSION=1.9.9
- DJANGO_VERSION=1.10

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
  exclude:
    # Django 1.7 is not supported on python 3.5.
    - python: 3.5
      env: DJANGO_VERSION=1.7.11

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- pip install -q Django==$DJANGO_VERSION

script: coverage run --source=webchat manage.py test

after_success:
- coveralls
- codecov
