language: python

sudo: required

python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3

env:
- DJANGO_VERSION=1.8.18
- DJANGO_VERSION=1.9.13
- DJANGO_VERSION=1.10.7
- DJANGO_VERSION=1.11.1

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3

# Install a recent nodejs
before_install:
- sudo apt-get remove nodejs
- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
- sudo apt-get install -y -q nodejs
- node --version
- which node
- /usr/bin/node --version

# Install various python dependencies
install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- pip install -q Django==$DJANGO_VERSION

# Run python tests with test coverage and build the webapp bundle
script:
- coverage run --source=webchat manage.py test
- cd webapp && npm install --silent && npm start && cd ..

after_success:
- coveralls
- codecov
