language: python

python:
- 3.5
- 3.6
- 3.7
- pypy3

env:
- DJANGO_VERSION=1.11.8  # LTS
- DJANGO_VERSION=2.0  # Current

matrix:
  allow_failures:
    - python: pypy3

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- pip install -q Django==$DJANGO_VERSION

script:
- coverage run --source=webchat manage.py test

after_success:
- coveralls
- codecov
