language: python

python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- pypy3

node_js:
- "node"

env:
- DJANGO_VERSION=1.7.11
- DJANGO_VERSION=1.8.7
- DJANGO_VERSION=1.9.9
- DJANGO_VERSION=1.10

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3
  exclude:
    # Django 1.7 is not supported on python 3.5+.
    - python: 3.5
      env: DJANGO_VERSION=1.7.11
    - python: 3.6
      env: DJANGO_VERSION=1.7.11

install:
- pip install -q -r requirements.txt
- pip install -q coveralls codecov
- pip install -q Django==$DJANGO_VERSION
- node --version
- npm --version
- cd webapp && npm install && npm start & cd ..

script: coverage run --source=webchat manage.py test

after_success:
- coveralls
- codecov
